/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 *Primer Taller en STM 2/03/22
 ******************************************************************************
 */

#include <stdint.h>

char var1=0;
int var2 =0;
short var3 =0;
long var4 =0;

uint8_t var5 =0;
int8_t var6 =0;
int16_t var7=0;
int64_t var9 =0;

int main(void)
{
	uint16_t testShift = 0b0000110101100110;
	uint16_t testMask = 0b0000000000110101;
    /* Loop forever */
	while(1){
		testMask <<= 3;

	}
	return 0;
}
